export const productCards = [
  {
    image: "images/moist-mousse.png",
    category: "для нормальной кожи",
    name: "Увлажняющий мусс",
    description: "Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.",
    compound: ["активные натуральные комплексы", "витамины С, А, РР, В И Е", "солнцезащитные компоненты"],
    priceLabel: "Цена",
    price: 2750,
  },
  {
    image: "images/moist-mask.png",
    category: "для нормальной кожи",
    name: "Увлажняющая маска",
    description: "Способствует удерживанию влаги в верхних слоях кожи.",
    compound: ["воски", "минералы", "масла"],
    priceLabel: "Цена",
    price: 3500,
  },
  {
    image: "images/cleansing-gel.png",
    category: "для нормальной кожи",
    name: "Гель для умывания",
    description: "Интенсивно очищает, не повреждает защитный барьер кожи.",
    compound: ["минералы", "витамины С, А, РР, В И Е", "солнцезащитные компоненты"],
    priceLabel: "Цена",
    price: 1650,
  },
  {
    image: "images/gift-set-1.png",
    category: "для нормальной кожи",
    name: "Подарочный набор №1",
    description: "Набор, состоящий из увлажняющего крема и маски.",
    compound: ["воски", "минералы", "масла"],
    priceLabel: "Цена",
    price:  4750,
  },
  {
    image: "images/gift-set-5.png",
    category: "для нормальной кожи",
    name: "Подарочный набор №5",
    description: "Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.",
    compound: ["воски", "минералы", "масла"],
    priceLabel: "Цена",
    price: 7520,
  },
];